# Makefile

# defaults
SIM ?= ghdl
TOPLEVEL_LANG ?= vhdl

# VHDL 2008
EXTRA_ARGS +=--std=08

# TOPLEVEL is the name of the toplevel module in your VHDL file
TOPLEVEL = shiftn

VHDL_SOURCES += ../src/$(TOPLEVEL).vhd
VHDL_SOURCES += ../src/dff.vhd

#VHDL_SOURCES += $(PWD)/../../hdl/*.vhdl

# create a waveform when running this script
SIM_ARGS +=--wave=$(TOPLEVEL).ghw
SIM_ARGS +=-gN=64

# MODULE is the basename of the Python test file
MODULE = tb_$(TOPLEVEL)

# include cocotb's make rules to take care of the simulator setup
include $(shell cocotb-config --makefiles)/Makefile.sim

# removing generated binary of top entity and .o-file on make clean
clean::
	-@rm -f $(TOPLEVEL)
	-@rm -f e~$(TOPLEVEL).o